describe("雲端筆記", function () {
    var response, jsonData;
    describe("取得筆記本與筆記", function () {
        jQuery.ajax({
            url: '../index.php?action=get-notes&type=notes',
            type: 'GET',
            data: {
                ticket: ticket
            },
            async: false,
            complete: function (returnInfo) {
                response = returnInfo;
                jsonData = JSON.parse(response.responseText);
            }
        });

        it("驗證 status - 要是 200", function () {
            expect(response.status).toEqual(200);
        });

        it("驗證 Note Data - 要有值", function () {
            expect(jsonData).toBeDefined();
        });

        it("驗證 Note Code - 要是 0", function () {
            expect(jsonData.code).toEqual(0);
        });

        it("驗證 Note message - type 是 string", function () {
            expect(typeof(jsonData.message)).toEqual('string');
        });

        it("驗證 Note Message - 要是'success'", function () {
            expect(jsonData.message).toEqual('success');
        });

        it("驗證 Note notebooks - 要有值", function () {
            expect(jsonData.data.notebooks).toBeDefined();
        });

        describe("驗證回傳資料的各項參數與是否符合API設定的型態", function () {
            describe("驗證 JSON Data > data > notebooks > book_id", function () {
                it("要有值", function () {
                    expect(jsonData.data.notebooks[0].folder_id).toBeDefined();
                });
                it("type須為string", function () {
                    expect(typeof(jsonData.data.notebooks[0].folder_id)).toEqual('string');
                });
            });
            describe("驗證 JSON Data > data > notebooks > folder_title", function () {
                it("要有值", function () {
                    expect(jsonData.data.notebooks[0].folder_title).toBeDefined();
                });
                it("type須為string", function () {
                    expect(typeof(jsonData.data.notebooks[0].folder_title)).toEqual('string');
                });
            });
            describe("驗證 JSON Data > data > notebooks > notes", function () {
                it("要有值", function () {
                    expect(jsonData.data.notebooks[0].notes).toBeDefined();
                });
                describe("驗證 JSON Data > data > notebooks > notes > note_id", function () {
                    it("要有值", function () {
                        expect(jsonData.data.notebooks[0].notes[0].note_id).toBeDefined();
                    });
                    it("type須為number", function () {
                        expect(typeof(jsonData.data.notebooks[0].notes[0].note_id)).toEqual('number');
                    });
                });
                describe("驗證 JSON Data > data > notebooks > notes > note_title", function () {
                    it("要有值", function () {
                        expect(jsonData.data.notebooks[0].notes[0].note_title).toBeDefined();
                    });
                    it("type須為string", function () {
                        expect(typeof(jsonData.data.notebooks[0].notes[0].note_title)).toEqual('string');
                    });
                });
                describe("驗證 JSON Data > data > notebooks > notes > note_content", function () {
                    if (jsonData.data.notebooks[0].notes[0].note_content != '') {
                        it("若有值，type須為string", function () {
                            expect(typeof(jsonData.data.notebooks[0].notes[0].note_content)).toEqual('string');
                        });
                    }
                });
                describe("驗證 JSON Data > data > notebooks > notes > note_time", function () {
                    it("要有值", function () {
                        expect(jsonData.data.notebooks[0].notes[0].note_time).toBeDefined();
                    });
                    it("type須為string", function () {
                        expect(typeof(jsonData.data.notebooks[0].notes[0].note_time)).toEqual('number');
                    });
                });
                describe("驗證 JSON Data > data > notebooks > notes > note_attachments", function () {
                    if (typeof(jsonData.data.notebooks[0].notes[0].note_attachments) === 'array') {
                        it("若有值，type須為string", function () {
                            expect(typeof(jsonData.data.notebooks[0].notes[0].note_attachments[0].filename)).toEqual('string');
                        });
                        describe("驗證 JSON Data > data > notebooks > notes > note_attachments > filename", function () {
                            it("type須為string", function () {
                                expect(typeof(jsonData.data.notebooks[0].notes[0].note_attachments[0].filename)).toEqual('string');
                            });
                        });
                        describe("驗證 JSON Data > data > notebooks > notes > note_attachments > href", function () {
                            it("type須為string", function () {
                                expect(typeof(jsonData.data.notebooks[0].notes[0].note_attachments[0].href)).toEqual('string');
                            });
                        });
                    }
                });
            });
        });
    });
    describe("新增筆記", function () {
        var response, jsonData;

        jQuery.ajax({
            url: '../index.php?action=note-handler&ticket=' + ticket,
            type: 'POST',
            data: JSON.stringify({
                folder_id: 'sys_notebook',
                title: '測試新增筆記',
                content: '這是測試用的筆記內容',

                attachments: [
                    {
                        filename: '',
                        base64: '/9j/4AAQSkZJRgABAQEAYABgAAD/4gv4SUNDX1BST0ZJTEUAAQEAAAvoAAAAAAIAAABtbnRyUkdCIFhZWiAH2QADABsAFQAkAB9hY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA9tYAAQAAAADTLQAAAAAp+D3er/JVrnhC+uTKgzkNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBkZXNjAAABRAAAAHliWFlaAAABwAAAABRiVFJDAAAB1AAACAxkbWRkAAAJ4AAAAIhnWFlaAAAKaAAAABRnVFJDAAAB1AAACAxsdW1pAAAKfAAAABRtZWFzAAAKkAAAACRia3B0AAAKtAAAABRyWFlaAAAKyAAAABRyVFJDAAAB1AAACAx0ZWNoAAAK3AAAAAx2dWVkAAAK6AAAAId3dHB0AAALcAAAABRjcHJ0AAALhAAAADdjaGFkAAALvAAAACxkZXNjAAAAAAAAAB9zUkdCIElFQzYxOTY2LTItMSBibGFjayBzY2FsZWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWFlaIAAAAAAAACSgAAAPhAAAts9jdXJ2AAAAAAAABAAAAAAFAAoADwAUABkAHgAjACgALQAyADcAOwBAAEUASgBPAFQAWQBeAGMAaABtAHIAdwB8AIEAhgCLAJAAlQCaAJ8ApACpAK4AsgC3ALwAwQDGAMsA0ADVANsA4ADlAOsA8AD2APsBAQEHAQ0BEwEZAR8BJQErATIBOAE+AUUBTAFSAVkBYAFnAW4BdQF8AYMBiwGSAZoBoQGpAbEBuQHBAckB0QHZAeEB6QHyAfoCAwIMAhQCHQImAi8COAJBAksCVAJdAmcCcQJ6AoQCjgKYAqICrAK2AsECywLVAuAC6wL1AwADCwMWAyEDLQM4A0MDTwNaA2YDcgN+A4oDlgOiA64DugPHA9MD4APsA/kEBgQTBCAELQQ7BEgEVQRjBHEEfgSMBJoEqAS2BMQE0wThBPAE/gUNBRwFKwU6BUkFWAVnBXcFhgWWBaYFtQXFBdUF5QX2BgYGFgYnBjcGSAZZBmoGewaMBp0GrwbABtEG4wb1BwcHGQcrBz0HTwdhB3QHhgeZB6wHvwfSB+UH+AgLCB8IMghGCFoIbgiCCJYIqgi+CNII5wj7CRAJJQk6CU8JZAl5CY8JpAm6Cc8J5Qn7ChEKJwo9ClQKagqBCpgKrgrFCtwK8wsLCyILOQtRC2kLgAuYC7ALyAvhC/kMEgwqDEMMXAx1DI4MpwzADNkM8w0NDSYNQA1aDXQNjg2pDcMN3g34DhMOLg5JDmQOfw6bDrYO0g7uDwkPJQ9BD14Peg+WD7MPzw/sEAkQJhBDEGEQfhCbELkQ1xD1ERMRMRFPEW0RjBGqEckR6BIHEiYSRRJkEoQSoxLDEuMTAxMjE0MTYxODE6QTxRPlFAYUJxRJFGoUixStFM4U8BUSFTQVVhV4FZsVvRXgFgMWJhZJFmwWjxayFtYW+hcdF0EXZReJF64X0hf3GBsYQBhlGIoYrxjVGPoZIBlFGWsZkRm3Gd0aBBoqGlEadxqeGsUa7BsUGzsbYxuKG7Ib2hwCHCocUhx7HKMczBz1HR4dRx1wHZkdwx3sHhYeQB5qHpQevh7pHxMfPh9pH5Qfvx/qIBUgQSBsIJggxCDwIRwhSCF1IaEhziH7IiciVSKCIq8i3SMKIzgjZiOUI8Ij8CQfJE0kfCSrJNolCSU4JWgllyXHJfcmJyZXJocmtyboJxgnSSd6J6sn3CgNKD8ocSiiKNQpBik4KWspnSnQKgIqNSpoKpsqzysCKzYraSudK9EsBSw5LG4soizXLQwtQS12Last4S4WLkwugi63Lu4vJC9aL5Evxy/+MDUwbDCkMNsxEjFKMYIxujHyMioyYzKbMtQzDTNGM38zuDPxNCs0ZTSeNNg1EzVNNYc1wjX9Njc2cjauNuk3JDdgN5w31zgUOFA4jDjIOQU5Qjl/Obw5+To2OnQ6sjrvOy07azuqO+g8JzxlPKQ84z0iPWE9oT3gPiA+YD6gPuA/IT9hP6I/4kAjQGRApkDnQSlBakGsQe5CMEJyQrVC90M6Q31DwEQDREdEikTORRJFVUWaRd5GIkZnRqtG8Ec1R3tHwEgFSEtIkUjXSR1JY0mpSfBKN0p9SsRLDEtTS5pL4kwqTHJMuk0CTUpNk03cTiVObk63TwBPSU+TT91QJ1BxULtRBlFQUZtR5lIxUnxSx1MTU19TqlP2VEJUj1TbVShVdVXCVg9WXFapVvdXRFeSV+BYL1h9WMtZGllpWbhaB1pWWqZa9VtFW5Vb5Vw1XIZc1l0nXXhdyV4aXmxevV8PX2Ffs2AFYFdgqmD8YU9homH1YklinGLwY0Njl2PrZEBklGTpZT1lkmXnZj1mkmboZz1nk2fpaD9olmjsaUNpmmnxakhqn2r3a09rp2v/bFdsr20IbWBtuW4SbmtuxG8eb3hv0XArcIZw4HE6cZVx8HJLcqZzAXNdc7h0FHRwdMx1KHWFdeF2Pnabdvh3VnezeBF4bnjMeSp5iXnnekZ6pXsEe2N7wnwhfIF84X1BfaF+AX5ifsJ/I3+Ef+WAR4CogQqBa4HNgjCCkoL0g1eDuoQdhICE44VHhauGDoZyhteHO4efiASIaYjOiTOJmYn+imSKyoswi5aL/IxjjMqNMY2Yjf+OZo7OjzaPnpAGkG6Q1pE/kaiSEZJ6kuOTTZO2lCCUipT0lV+VyZY0lp+XCpd1l+CYTJi4mSSZkJn8mmia1ZtCm6+cHJyJnPedZJ3SnkCerp8dn4uf+qBpoNihR6G2oiailqMGo3aj5qRWpMelOKWpphqmi6b9p26n4KhSqMSpN6mpqhyqj6sCq3Wr6axcrNCtRK24ri2uoa8Wr4uwALB1sOqxYLHWskuywrM4s660JbSctRO1irYBtnm28Ldot+C4WbjRuUq5wro7urW7LrunvCG8m70VvY++Cr6Evv+/er/1wHDA7MFnwePCX8Lbw1jD1MRRxM7FS8XIxkbGw8dBx7/IPci8yTrJuco4yrfLNsu2zDXMtc01zbXONs62zzfPuNA50LrRPNG+0j/SwdNE08bUSdTL1U7V0dZV1tjXXNfg2GTY6Nls2fHadtr724DcBdyK3RDdlt4c3qLfKd+v4DbgveFE4cziU+Lb42Pj6+Rz5PzlhOYN5pbnH+ep6DLovOlG6dDqW+rl63Dr++yG7RHtnO4o7rTvQO/M8Fjw5fFy8f/yjPMZ86f0NPTC9VD13vZt9vv3ivgZ+Kj5OPnH+lf65/t3/Af8mP0p/br+S/7c/23//2Rlc2MAAAAAAAAALklFQyA2MTk2Ni0yLTEgRGVmYXVsdCBSR0IgQ29sb3VyIFNwYWNlIC0gc1JHQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYWVogAAAAAAAAYpkAALeFAAAY2lhZWiAAAAAAAAAAAABQAAAAAAAAbWVhcwAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACWFlaIAAAAAAAAAMWAAADMwAAAqRYWVogAAAAAAAAb6IAADj1AAADkHNpZyAAAAAAQ1JUIGRlc2MAAAAAAAAALVJlZmVyZW5jZSBWaWV3aW5nIENvbmRpdGlvbiBpbiBJRUMgNjE5NjYtMi0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYWVogAAAAAAAA9tYAAQAAAADTLXRleHQAAAAAQ29weXJpZ2h0IEludGVybmF0aW9uYWwgQ29sb3IgQ29uc29ydGl1bSwgMjAwOQAAc2YzMgAAAAAAAQxEAAAF3///8yYAAAeUAAD9j///+6H///2iAAAD2wAAwHX/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABgAGADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD61mvzuC+YiHBbGRnA6nnsMjNQR3CXMayxzrKj9GVgQfoRx2NYel6dB9oikjtYJrSa2YGU4xJuIJXAGMAZ5Oc+vJNQwSJa263klk5hBRYEEhBiRgFOQSecMT7kcnJJNqslsjnlQct2dNC0PmDzMEHOPeud+JnjrQvBWg/ablBcX86sLKyD7GmYYyzNg7I13LvfBxkAB3dEeHWmt7HTbrWbi4aJIYpGld3Cx26AAs5LEAKFUHOcDnOAcj5Y8e65fXumr4h1ozQ3Gpq13crNuMlrAuXitcYHyxK5GAoywZyA7tnooQ9vLskTKPsl3uJ4k+KfjzxJrE9tceI7qCyjj3PDphewSOY8IUeJ/O+5lnSSV1y6kDG0LyFzpmkz7fM0bSRtzjy7GJOvrtUZ6d6bo8EsNgjXC7bmX97cDIOJG5IyM5A4UcnAUDJxVyvVhSglsc8pu9kyDQ/CUc93u0Kye0u4wSLi0l8iSIEEEiQEFcjIPIyM54zXS3Wt+PPBK6S99rKeItFUGGOOVy+AJDI8fnMglWQlmwz7wA/CEAASfDzULi113yBFE9oALqZhGDINrxgAEg4HPABGSxyTwKveOrbUR4Dure2vJb6WKSJNQc7g8qR7gzlTk4DhckkkFSTgEgctSUXiFRklZntUMDGWXyxKcrq/po1/nv0ses6T4n8I+JfDulahpkF/LGLdo5IvtsYltnEshMUoEZw43A8cFWUjIIY62qS6MLLSi9hqBU2jFAL1AQPPl4J8o5OcnIxwQMcZPyf4B8Rp4V8U2uq3LTnTCwj1KKKTZ5kBBG45R+Yy3mDCkkKygjea+sNUl0cWOlF7C/Km0YoBeqCB58vBPlHJzk5GOCBjjJ5MZhXh6nL06M4aFVVY3DVJdGFjpRew1AqbRigF6gIHny8E+UcnOTkY4IGOMk1SXRhY6UXsNQKm0YoBeoCB58vBPlHJzk5GOCBjjJdqDaVLa6PEum6lI8lqVhRLxNxzPKAP9UcknOMAdQMcZLvEKWFi9pYX+j6nBNbW+3ab2PkGR3BDCMhh8x5GOQRjIJPIbHZ2W59FRkgD+Ur2giZxl9pwpHAAJIyOOMgds1YuZ4LedFaJzcRTiQyKh2ZI4yc9SAeB6jpnk0PU/DWq3t/pei6xp9/dWUyrfwWs5le1lyUAlC5MbZRhhsH5TkcGtOXT4bmaDzYt0ka5RmRxtBxnnGM/IOpzwD35nl1H0seR/GzUbuT4b6lboGktb5U02SVoyCIrm8itmIOBhgk0gGcjKgkHpXz98ZmY2V6hY7RpshCk8AkPk49TgfkK+nv2hoxH8Krlox97UtJB+UjI/tC1PRgPUfyPQ18zfFazutQFzZ6Zbz6jfSaa4FnZQvPcBTuAcxoCwQsQu8jaCQCQSM+lgmoUpNuxzVk3ONtTGop9vpfiG9jaWzsrW3RZGjIvZ2SQlSQwKIrFcEYIYhgQQVBFW5PCmpxlp7rxLbQ2qfNKUsAm1QMsQzSMFIAJyQQOpBHFazzXDQ05rs78Pw3mOIhzxp2T6tpD/C43a6jmcQxwQvJOckEqQQB6EbsE5IxtzyQBV3xz4g0200S60zRrgySX7s0hEgfZHJJ5rKGUgAbgAAQSQzEnBAHKaxbeBrSNbi98dXUmW2/up4Jmycn7qRkgcHnGBwO4p03hu3MMM+naR8RtWtriFZormz0cNG6tyCC0K5BHIIyCCMGuZZhhp1lUfNp5dj05ZficLhHh1KF3e75rvW2yXp5nOOqujI6qysCCrDIIPUEdxX1J4A1w3nw58LNf6bZ3kyaPagzzSTtJISgdmYiQZJZmJPqT2wK+PtfuPFeiF7i+8Napp1m0gRDqds4YNj7pcIgJ4YgYBxnrjNfTf7OXxW+E2u+HNA8H61DJomv2tpBZD7ZM4t7x0QqDHKDhSQgO1wnzOEUueTtmGMp4pRdPpufOYfDToNqXyPRJtaEkUKppVlC9uhS3ljeYPF8xYEHzDyGYkEg8+wxRc65NfTNcapaW2oznAEk5kUqoGAoCOoA6ngdST3rsdR0jwlZaH/bLadJLa7EcGOR9zBiACAWHqDzijRtL8Fax539nQef5WPM+eZcZzjqRnoenpXmXOk47TNO1fS9FsdK0y3f/AISH4eXSW0ESgQyanozgBMklS4aFcEnZEbq3ySFjJr1bT7uTxHpFlrGkXkVxpV/FHe2M3zxsY3jDxsQVBwcgkEAjP4DzjxDeazeeKbfxFoyLPc6JGbdrUFQl5DNJE11bgtwWZIkKksoEiR5IQuC/wtrVrpXiRV0iVZvDHi2Aa1osrAqqSugaaEAkBN64mCYLs63btjFZqrFxuieZWuO+MVteeINesfD/AIha707RZ7OK40/7PNs87UkeR3DMMh2hWOGWOJxsfMjFJPL/AHXPfs72ep2vwcj1ee4/03UbmS41GK9tt8q3Sv5EgOSAoBhA2FfkHyAjAx6F4ltYPEOmizvB5UkT+ba3MPE1rMAQJYy2QCASCCCrKzI4ZGZTzHhC3n8Ia3c+Grq/udUsNZSW9sprxY1b7WOZ4CIkjjXeu2ZERdzMt3IxyM1yVKnOmlJ27G9KpFtKx49pfgfxn4x+LmnXHivSbnSQkpm8Q6qNcAh1eFQiIkfkJEY1UK+wOXmxKodiFyvcaX8GfAGmazrl1pulQ6lp1863Pna1bC6uIpS7ZiiabOIyGyCyGQlGLOw2kei+ZYkktazgnkhJwFH5qSB6ZJPua5bTfEniDRNduE1Dwo8umz3jqt1ZXkk7ZJCwv5JBKIIhGjlSoEhlcIELSHmlinKLSaX5ncoS0V3b8Dkvibb+N/D2gW2h+AfDm7Q7ixuF+0aReLp9xY3bsVjYiNNxjRm84rCFZyQHOwESdF4b0fUNG+GOgz3Xizxs3jSddjSf2pcXscrEsQbmGaR4YYtu13wY5MKURt52szxNqus6rcNpmk+GdTa3glEgum1J9PaCYjCGP5WEyqGUuHDRkAfu5mUxjtzJYjlLWckc4ecFSfcBQSPXBB9xTWL5aaWmpEsO3K7ueP8A7S+mJe+A7+4aAmdzthtrZNjTSMFjR8AENuaUqAqjJQgHJJrh7X4YfD2PxgYbTw9HPDbW4kn3zTSJBcq6GKM5kwd6PIzqwfAji4QOS/qF9oOpfEnxDd2tjfy6bZaRsnE0aptFyz7oocMkiEKm+V1Ybw72zgkkmtj/AIRzTUvbrRtDCZsxJLcXU777vUbkIAxIwMn92FAUBEAwoC7VDwUJaTvprp623/rqLEzilyW179jrdCsNa8S6Xatrl00OmKqYt1BD3YUHDuxOQCcHrzjIA4J7K0tLWzjMdpbQ28ZO4rEgQE4AzgAc4A59qzPh9crf+EbGQshkiQwsqH7uwkAEZOCVCk/XPQit/wApfU16nPFHAeC3eorPpS2nlN5zTmeaUnAZzkcDtwR6dDx3qoLRrfR003SbiMG+1NLvS5JzsXTNYK5VGYD5LS6KGJwuHLzsuW88+XteL7eGBbMQ/ZMEOMQSxvgAg87ScckkZ9T71Z0u20G88J3GmalNa+VqEMkF5E3nBnjcMhUsqnGVJxg5Gc8HNcX1inTpqbaSb7gqcpaRi/Q6Hw1rVtrmiWuqWqSxR3KBjDMAJIHHDRSAE7ZFYFGXJIZSDyDVvVLKz1XT5bDUIjLBJgkByjKwIZXVgQUdWAZXUgqQCCCAR5h4Q8V2WjeMr3wvrmsLNe3ifalaGAD7TdJHGbm4jjYxhIptyzBVU4nF8CSEV27G68Rwyiez0i6WO4ht/tV3d38ASz062BObidhLkDCtsQEGQqQCirJJHze77VQjLfVencj2FRa22KU03iXQmMN/pFzr1jH93UrAxtOIxyXntzsO8AgYtxIXKsQkeVjrKPjHwhAxguPHEOjyr96y1KaO2uYs8jdHcqJlyMEbgMggjgivO/H3xB1KW7EHhPx3rt7blHS+e40+KzhebJDxxReSl1CikMuTL5g6BwVDtzmh+M9V03Uv7Q1DSLbXp/JeGJrjWdQUwoxRmC+fLcD5jHGSQFI24JIPFVsujUjdrXpbQ9LC46rSdm1bzPYLbxh4bnvVKeOLPVmViYbDSplu7mcjOCIrdTI4AySgUgAEk4Bxa1HUfFOuQSWWkeGtV0q1mBV9RvYVWTyz0eGAByWIyMTCMoSpKOQyDxTWvGWq6jqbahp2kwaBO8SwzNb63qDeciFigbyJbcDaXkIJDE7z0xzv+BvivcWWuwaN4v8AiJrVg08YGmLBp0V7Esg4WOaMQvdSxscKCJhKcEFySXXOnlfJT93RvvqaYjMZ1J30svkenad4eu9Ps47Sz0i8jhTJAMTsSSSWZmOSzEkksSSSSSSSTS3GianIhK6XeF+2IGyf0rt9B18mSOw1a605bl7cXVrewXCCz1S3ONtzbMznKkMu9MsYyyglkeKSTf8AtMQiErtsiJG2RgVR85I2seGBHIIJBHNcFLKHRrc6qPmWvqZTzCUocrgjyq30LWo7y1Nvp19HMHBDiN1CkEYO4gY575FdbpVl43juGYX0sOUI3XNwJFPI4A+bB98evPPPYJIR3yKmjDSfcVm4zwCTXZLAe1acpyuuxjHGNJqMV8zxPVoSt/cLPbtZeSoYW8gYNuIHAyMgckjd0AwSTybFzpGoaTFCNQtZLc3CeagYdRxwfQjjIOCMjIGafNZQQI6XN/vLurPbW5DqcEjJfJUHaxwVD4yQQORUqapNHcwSwQW8EcEyypCikLuU5BYklm5zjJJAJAwDivBxmKoyw0aN7Xtfy/p3PToU6iqOaV/N9fQ85+Lujy3GkWviPS2K6/oMwuNNzI6rMzMoa3Kry/mgBAgwWYqoIDEG14F8Qaf4w8MaOmk3D3GmW8S3+skqVF1rUpWRkYMqsy2oCJGWLqVaLBLQKa9N+Kfi7TdT0rw7cyPLbWVnrKXOrRyAtGsK20+yRsAhkW4MD5I+UoJCFCFh4lc+LvC2g/FG3Hw/sf7cg1s3EuuQWGoNsuLiSVHjkY5ZXI2TFYsoEDSNmNSz16mHo8uEdKjU5m07Stst7eX/AATKUnKpzzjbyOKuP+Qtq/8A2F77/wBKpabXtVvpfw003UvEurfETRbhrHU8Ti/sFuhHaqoiMkZgtcGIlomlNwqjd5kqOVBAl9Qn+F/wc8IWUWqahY2Gm21hI8v2jVdUkeJTKFiPmm4kZXU4UKr5CsSVAZiT72ExFOvRjODumedXhKE2mrHyLXC28zTfHzQIriRhFFq1igKoCVQyRsccjJyxPJHpkDp93QfCv4QeJNOvNeggt9V07VLiOdLnTdSeO3TykMISE2rIqpkOWVfvOSWyVXb44/hn4X654n0jXvAnhW6trLS3Eseq3y3AOoKYmKBEnYu4DSh/PcBh5UaIWXmN4vEQw9GU5vZf0goU5VJqKOg8ST6TpunXWiy+IYNNsL0m/wBGutVZLW1sNYiLSbS4LlUuUMokxsGEkAy9ySd3w14msp9Pt9U0fT5oFuIssLm5kE8bZ+aJvKZACrAqyckMpBPGBzS3+haH43n1rxTLZW1uthAmlXV5t2xThrgTrG7cROyNCCMguF4yEbanhJlmn1y+tV26Xe6m9xp20AI0Jij3MgHAVpRKwIGHLFwSHDH5PF15SwdOoviSVn69PX/gnsU6CVRp7dj02x8bXDOsM1vaWcYOFaCAbFycncpBJBP90ggEnDHArrbXUJL2HMhkVlIGGYMCcAgggkEEEEEdQc9DXnOl6Hc3LJLcxSRQMA4GQJJAcY2g8gHP3yNowepAB7ixjMMITcueOBnCgAKAM84AAGSSTjJOa78qr4qdJvEfLoeZj40YSXs/meYUUUV8OfSDoyEkV2RZFUglWJAYA9Dgg4PsQfert3Lotzei+n028e5VSiyG6j3Kp25VSIvlU7V+UYHyrxwMUK8a8dXPxJ1nxFf2On6L4sjsLSXbEmjWNxIrqMhZWngUklwSdgYKOAVLKSfbyPAVsfWdCnNQ7tnJjKkKUeeSb9LnqXxPl0k/DXxQI7K9Vzo94FZrtWAPkPgkCMZGe2R9RXo37SH/ACJ6/wDYS0n/ANOUFfFN54I1e2bbcfD3XonIztk8OXCnHrgxDjr+VdH8HvBFzP8AEvRbi+8LX2n2VpJJPcXFxpDRKmIXCEeYEDMJTGQAcg/MBhSR95DJ4ZXQmvbRm3rpZHh1MUqs02rLz1Prn4Jf8kaA/wCovqv/AKdLivLPhTaXV38PfDUVrbTTyLo1qxWNCxA8lBnAB4yRz71458XfBU0XxK1q4svCV/eWV3LFPbzQaW04kBhjEjExIwUmRZCVJzzk5yGPKN4RvCMf8INrPHp4fn/+N06+R0czwtNyrxj1tfX0CjjfYTcoq59iWvh2Zjm7uoYRk5WIiZyMcEFTs69iwOATjpnZ07T7KxKtBHukGP30gDPnjkDonIBGAWB6MRXzl8H/ABH8UdO8V2Omz6f4o1PSbqcLcx6va3AWJCQGmW4mXKFQpIQsVbBAXe4I+ko50cdcHGSDXhyyyhgZ8sbN9HuZ18fWqaN79C5E4yxGcsSzEnJJPUknqfc1Mj++D6iqQOCCKkWTH3vzFaqTvqcVz//Z'
                    },
                    {
                        filename: '',
                        base64: '/9j/4AAQSkZJRgABAQEAYABgAAD/4gv4SUNDX1BST0ZJTEUAAQEAAAvoAAAAAAIAAABtbnRyUkdCIFhZWiAH2QADABsAFQAkAB9hY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA9tYAAQAAAADTLQAAAAAp+D3er/JVrnhC+uTKgzkNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBkZXNjAAABRAAAAHliWFlaAAABwAAAABRiVFJDAAAB1AAACAxkbWRkAAAJ4AAAAIhnWFlaAAAKaAAAABRnVFJDAAAB1AAACAxsdW1pAAAKfAAAABRtZWFzAAAKkAAAACRia3B0AAAKtAAAABRyWFlaAAAKyAAAABRyVFJDAAAB1AAACAx0ZWNoAAAK3AAAAAx2dWVkAAAK6AAAAId3dHB0AAALcAAAABRjcHJ0AAALhAAAADdjaGFkAAALvAAAACxkZXNjAAAAAAAAAB9zUkdCIElFQzYxOTY2LTItMSBibGFjayBzY2FsZWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWFlaIAAAAAAAACSgAAAPhAAAts9jdXJ2AAAAAAAABAAAAAAFAAoADwAUABkAHgAjACgALQAyADcAOwBAAEUASgBPAFQAWQBeAGMAaABtAHIAdwB8AIEAhgCLAJAAlQCaAJ8ApACpAK4AsgC3ALwAwQDGAMsA0ADVANsA4ADlAOsA8AD2APsBAQEHAQ0BEwEZAR8BJQErATIBOAE+AUUBTAFSAVkBYAFnAW4BdQF8AYMBiwGSAZoBoQGpAbEBuQHBAckB0QHZAeEB6QHyAfoCAwIMAhQCHQImAi8COAJBAksCVAJdAmcCcQJ6AoQCjgKYAqICrAK2AsECywLVAuAC6wL1AwADCwMWAyEDLQM4A0MDTwNaA2YDcgN+A4oDlgOiA64DugPHA9MD4APsA/kEBgQTBCAELQQ7BEgEVQRjBHEEfgSMBJoEqAS2BMQE0wThBPAE/gUNBRwFKwU6BUkFWAVnBXcFhgWWBaYFtQXFBdUF5QX2BgYGFgYnBjcGSAZZBmoGewaMBp0GrwbABtEG4wb1BwcHGQcrBz0HTwdhB3QHhgeZB6wHvwfSB+UH+AgLCB8IMghGCFoIbgiCCJYIqgi+CNII5wj7CRAJJQk6CU8JZAl5CY8JpAm6Cc8J5Qn7ChEKJwo9ClQKagqBCpgKrgrFCtwK8wsLCyILOQtRC2kLgAuYC7ALyAvhC/kMEgwqDEMMXAx1DI4MpwzADNkM8w0NDSYNQA1aDXQNjg2pDcMN3g34DhMOLg5JDmQOfw6bDrYO0g7uDwkPJQ9BD14Peg+WD7MPzw/sEAkQJhBDEGEQfhCbELkQ1xD1ERMRMRFPEW0RjBGqEckR6BIHEiYSRRJkEoQSoxLDEuMTAxMjE0MTYxODE6QTxRPlFAYUJxRJFGoUixStFM4U8BUSFTQVVhV4FZsVvRXgFgMWJhZJFmwWjxayFtYW+hcdF0EXZReJF64X0hf3GBsYQBhlGIoYrxjVGPoZIBlFGWsZkRm3Gd0aBBoqGlEadxqeGsUa7BsUGzsbYxuKG7Ib2hwCHCocUhx7HKMczBz1HR4dRx1wHZkdwx3sHhYeQB5qHpQevh7pHxMfPh9pH5Qfvx/qIBUgQSBsIJggxCDwIRwhSCF1IaEhziH7IiciVSKCIq8i3SMKIzgjZiOUI8Ij8CQfJE0kfCSrJNolCSU4JWgllyXHJfcmJyZXJocmtyboJxgnSSd6J6sn3CgNKD8ocSiiKNQpBik4KWspnSnQKgIqNSpoKpsqzysCKzYraSudK9EsBSw5LG4soizXLQwtQS12Last4S4WLkwugi63Lu4vJC9aL5Evxy/+MDUwbDCkMNsxEjFKMYIxujHyMioyYzKbMtQzDTNGM38zuDPxNCs0ZTSeNNg1EzVNNYc1wjX9Njc2cjauNuk3JDdgN5w31zgUOFA4jDjIOQU5Qjl/Obw5+To2OnQ6sjrvOy07azuqO+g8JzxlPKQ84z0iPWE9oT3gPiA+YD6gPuA/IT9hP6I/4kAjQGRApkDnQSlBakGsQe5CMEJyQrVC90M6Q31DwEQDREdEikTORRJFVUWaRd5GIkZnRqtG8Ec1R3tHwEgFSEtIkUjXSR1JY0mpSfBKN0p9SsRLDEtTS5pL4kwqTHJMuk0CTUpNk03cTiVObk63TwBPSU+TT91QJ1BxULtRBlFQUZtR5lIxUnxSx1MTU19TqlP2VEJUj1TbVShVdVXCVg9WXFapVvdXRFeSV+BYL1h9WMtZGllpWbhaB1pWWqZa9VtFW5Vb5Vw1XIZc1l0nXXhdyV4aXmxevV8PX2Ffs2AFYFdgqmD8YU9homH1YklinGLwY0Njl2PrZEBklGTpZT1lkmXnZj1mkmboZz1nk2fpaD9olmjsaUNpmmnxakhqn2r3a09rp2v/bFdsr20IbWBtuW4SbmtuxG8eb3hv0XArcIZw4HE6cZVx8HJLcqZzAXNdc7h0FHRwdMx1KHWFdeF2Pnabdvh3VnezeBF4bnjMeSp5iXnnekZ6pXsEe2N7wnwhfIF84X1BfaF+AX5ifsJ/I3+Ef+WAR4CogQqBa4HNgjCCkoL0g1eDuoQdhICE44VHhauGDoZyhteHO4efiASIaYjOiTOJmYn+imSKyoswi5aL/IxjjMqNMY2Yjf+OZo7OjzaPnpAGkG6Q1pE/kaiSEZJ6kuOTTZO2lCCUipT0lV+VyZY0lp+XCpd1l+CYTJi4mSSZkJn8mmia1ZtCm6+cHJyJnPedZJ3SnkCerp8dn4uf+qBpoNihR6G2oiailqMGo3aj5qRWpMelOKWpphqmi6b9p26n4KhSqMSpN6mpqhyqj6sCq3Wr6axcrNCtRK24ri2uoa8Wr4uwALB1sOqxYLHWskuywrM4s660JbSctRO1irYBtnm28Ldot+C4WbjRuUq5wro7urW7LrunvCG8m70VvY++Cr6Evv+/er/1wHDA7MFnwePCX8Lbw1jD1MRRxM7FS8XIxkbGw8dBx7/IPci8yTrJuco4yrfLNsu2zDXMtc01zbXONs62zzfPuNA50LrRPNG+0j/SwdNE08bUSdTL1U7V0dZV1tjXXNfg2GTY6Nls2fHadtr724DcBdyK3RDdlt4c3qLfKd+v4DbgveFE4cziU+Lb42Pj6+Rz5PzlhOYN5pbnH+ep6DLovOlG6dDqW+rl63Dr++yG7RHtnO4o7rTvQO/M8Fjw5fFy8f/yjPMZ86f0NPTC9VD13vZt9vv3ivgZ+Kj5OPnH+lf65/t3/Af8mP0p/br+S/7c/23//2Rlc2MAAAAAAAAALklFQyA2MTk2Ni0yLTEgRGVmYXVsdCBSR0IgQ29sb3VyIFNwYWNlIC0gc1JHQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYWVogAAAAAAAAYpkAALeFAAAY2lhZWiAAAAAAAAAAAABQAAAAAAAAbWVhcwAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACWFlaIAAAAAAAAAMWAAADMwAAAqRYWVogAAAAAAAAb6IAADj1AAADkHNpZyAAAAAAQ1JUIGRlc2MAAAAAAAAALVJlZmVyZW5jZSBWaWV3aW5nIENvbmRpdGlvbiBpbiBJRUMgNjE5NjYtMi0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYWVogAAAAAAAA9tYAAQAAAADTLXRleHQAAAAAQ29weXJpZ2h0IEludGVybmF0aW9uYWwgQ29sb3IgQ29uc29ydGl1bSwgMjAwOQAAc2YzMgAAAAAAAQxEAAAF3///8yYAAAeUAAD9j///+6H///2iAAAD2wAAwHX/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABgAGADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD61mvzuC+YiHBbGRnA6nnsMjNQR3CXMayxzrKj9GVgQfoRx2NYel6dB9oikjtYJrSa2YGU4xJuIJXAGMAZ5Oc+vJNQwSJa263klk5hBRYEEhBiRgFOQSecMT7kcnJJNqslsjnlQct2dNC0PmDzMEHOPeud+JnjrQvBWg/ablBcX86sLKyD7GmYYyzNg7I13LvfBxkAB3dEeHWmt7HTbrWbi4aJIYpGld3Cx26AAs5LEAKFUHOcDnOAcj5Y8e65fXumr4h1ozQ3Gpq13crNuMlrAuXitcYHyxK5GAoywZyA7tnooQ9vLskTKPsl3uJ4k+KfjzxJrE9tceI7qCyjj3PDphewSOY8IUeJ/O+5lnSSV1y6kDG0LyFzpmkz7fM0bSRtzjy7GJOvrtUZ6d6bo8EsNgjXC7bmX97cDIOJG5IyM5A4UcnAUDJxVyvVhSglsc8pu9kyDQ/CUc93u0Kye0u4wSLi0l8iSIEEEiQEFcjIPIyM54zXS3Wt+PPBK6S99rKeItFUGGOOVy+AJDI8fnMglWQlmwz7wA/CEAASfDzULi113yBFE9oALqZhGDINrxgAEg4HPABGSxyTwKveOrbUR4Dure2vJb6WKSJNQc7g8qR7gzlTk4DhckkkFSTgEgctSUXiFRklZntUMDGWXyxKcrq/po1/nv0ses6T4n8I+JfDulahpkF/LGLdo5IvtsYltnEshMUoEZw43A8cFWUjIIY62qS6MLLSi9hqBU2jFAL1AQPPl4J8o5OcnIxwQMcZPyf4B8Rp4V8U2uq3LTnTCwj1KKKTZ5kBBG45R+Yy3mDCkkKygjea+sNUl0cWOlF7C/Km0YoBeqCB58vBPlHJzk5GOCBjjJ5MZhXh6nL06M4aFVVY3DVJdGFjpRew1AqbRigF6gIHny8E+UcnOTkY4IGOMk1SXRhY6UXsNQKm0YoBeoCB58vBPlHJzk5GOCBjjJdqDaVLa6PEum6lI8lqVhRLxNxzPKAP9UcknOMAdQMcZLvEKWFi9pYX+j6nBNbW+3ab2PkGR3BDCMhh8x5GOQRjIJPIbHZ2W59FRkgD+Ur2giZxl9pwpHAAJIyOOMgds1YuZ4LedFaJzcRTiQyKh2ZI4yc9SAeB6jpnk0PU/DWq3t/pei6xp9/dWUyrfwWs5le1lyUAlC5MbZRhhsH5TkcGtOXT4bmaDzYt0ka5RmRxtBxnnGM/IOpzwD35nl1H0seR/GzUbuT4b6lboGktb5U02SVoyCIrm8itmIOBhgk0gGcjKgkHpXz98ZmY2V6hY7RpshCk8AkPk49TgfkK+nv2hoxH8Krlox97UtJB+UjI/tC1PRgPUfyPQ18zfFazutQFzZ6Zbz6jfSaa4FnZQvPcBTuAcxoCwQsQu8jaCQCQSM+lgmoUpNuxzVk3ONtTGop9vpfiG9jaWzsrW3RZGjIvZ2SQlSQwKIrFcEYIYhgQQVBFW5PCmpxlp7rxLbQ2qfNKUsAm1QMsQzSMFIAJyQQOpBHFazzXDQ05rs78Pw3mOIhzxp2T6tpD/C43a6jmcQxwQvJOckEqQQB6EbsE5IxtzyQBV3xz4g0200S60zRrgySX7s0hEgfZHJJ5rKGUgAbgAAQSQzEnBAHKaxbeBrSNbi98dXUmW2/up4Jmycn7qRkgcHnGBwO4p03hu3MMM+naR8RtWtriFZormz0cNG6tyCC0K5BHIIyCCMGuZZhhp1lUfNp5dj05ZficLhHh1KF3e75rvW2yXp5nOOqujI6qysCCrDIIPUEdxX1J4A1w3nw58LNf6bZ3kyaPagzzSTtJISgdmYiQZJZmJPqT2wK+PtfuPFeiF7i+8Napp1m0gRDqds4YNj7pcIgJ4YgYBxnrjNfTf7OXxW+E2u+HNA8H61DJomv2tpBZD7ZM4t7x0QqDHKDhSQgO1wnzOEUueTtmGMp4pRdPpufOYfDToNqXyPRJtaEkUKppVlC9uhS3ljeYPF8xYEHzDyGYkEg8+wxRc65NfTNcapaW2oznAEk5kUqoGAoCOoA6ngdST3rsdR0jwlZaH/bLadJLa7EcGOR9zBiACAWHqDzijRtL8Fax539nQef5WPM+eZcZzjqRnoenpXmXOk47TNO1fS9FsdK0y3f/AISH4eXSW0ESgQyanozgBMklS4aFcEnZEbq3ySFjJr1bT7uTxHpFlrGkXkVxpV/FHe2M3zxsY3jDxsQVBwcgkEAjP4DzjxDeazeeKbfxFoyLPc6JGbdrUFQl5DNJE11bgtwWZIkKksoEiR5IQuC/wtrVrpXiRV0iVZvDHi2Aa1osrAqqSugaaEAkBN64mCYLs63btjFZqrFxuieZWuO+MVteeINesfD/AIha707RZ7OK40/7PNs87UkeR3DMMh2hWOGWOJxsfMjFJPL/AHXPfs72ep2vwcj1ee4/03UbmS41GK9tt8q3Sv5EgOSAoBhA2FfkHyAjAx6F4ltYPEOmizvB5UkT+ba3MPE1rMAQJYy2QCASCCCrKzI4ZGZTzHhC3n8Ia3c+Grq/udUsNZSW9sprxY1b7WOZ4CIkjjXeu2ZERdzMt3IxyM1yVKnOmlJ27G9KpFtKx49pfgfxn4x+LmnXHivSbnSQkpm8Q6qNcAh1eFQiIkfkJEY1UK+wOXmxKodiFyvcaX8GfAGmazrl1pulQ6lp1863Pna1bC6uIpS7ZiiabOIyGyCyGQlGLOw2kei+ZYkktazgnkhJwFH5qSB6ZJPua5bTfEniDRNduE1Dwo8umz3jqt1ZXkk7ZJCwv5JBKIIhGjlSoEhlcIELSHmlinKLSaX5ncoS0V3b8Dkvibb+N/D2gW2h+AfDm7Q7ixuF+0aReLp9xY3bsVjYiNNxjRm84rCFZyQHOwESdF4b0fUNG+GOgz3Xizxs3jSddjSf2pcXscrEsQbmGaR4YYtu13wY5MKURt52szxNqus6rcNpmk+GdTa3glEgum1J9PaCYjCGP5WEyqGUuHDRkAfu5mUxjtzJYjlLWckc4ecFSfcBQSPXBB9xTWL5aaWmpEsO3K7ueP8A7S+mJe+A7+4aAmdzthtrZNjTSMFjR8AENuaUqAqjJQgHJJrh7X4YfD2PxgYbTw9HPDbW4kn3zTSJBcq6GKM5kwd6PIzqwfAji4QOS/qF9oOpfEnxDd2tjfy6bZaRsnE0aptFyz7oocMkiEKm+V1Ybw72zgkkmtj/AIRzTUvbrRtDCZsxJLcXU777vUbkIAxIwMn92FAUBEAwoC7VDwUJaTvprp623/rqLEzilyW179jrdCsNa8S6Xatrl00OmKqYt1BD3YUHDuxOQCcHrzjIA4J7K0tLWzjMdpbQ28ZO4rEgQE4AzgAc4A59qzPh9crf+EbGQshkiQwsqH7uwkAEZOCVCk/XPQit/wApfU16nPFHAeC3eorPpS2nlN5zTmeaUnAZzkcDtwR6dDx3qoLRrfR003SbiMG+1NLvS5JzsXTNYK5VGYD5LS6KGJwuHLzsuW88+XteL7eGBbMQ/ZMEOMQSxvgAg87ScckkZ9T71Z0u20G88J3GmalNa+VqEMkF5E3nBnjcMhUsqnGVJxg5Gc8HNcX1inTpqbaSb7gqcpaRi/Q6Hw1rVtrmiWuqWqSxR3KBjDMAJIHHDRSAE7ZFYFGXJIZSDyDVvVLKz1XT5bDUIjLBJgkByjKwIZXVgQUdWAZXUgqQCCCAR5h4Q8V2WjeMr3wvrmsLNe3ifalaGAD7TdJHGbm4jjYxhIptyzBVU4nF8CSEV27G68Rwyiez0i6WO4ht/tV3d38ASz062BObidhLkDCtsQEGQqQCirJJHze77VQjLfVencj2FRa22KU03iXQmMN/pFzr1jH93UrAxtOIxyXntzsO8AgYtxIXKsQkeVjrKPjHwhAxguPHEOjyr96y1KaO2uYs8jdHcqJlyMEbgMggjgivO/H3xB1KW7EHhPx3rt7blHS+e40+KzhebJDxxReSl1CikMuTL5g6BwVDtzmh+M9V03Uv7Q1DSLbXp/JeGJrjWdQUwoxRmC+fLcD5jHGSQFI24JIPFVsujUjdrXpbQ9LC46rSdm1bzPYLbxh4bnvVKeOLPVmViYbDSplu7mcjOCIrdTI4AySgUgAEk4Bxa1HUfFOuQSWWkeGtV0q1mBV9RvYVWTyz0eGAByWIyMTCMoSpKOQyDxTWvGWq6jqbahp2kwaBO8SwzNb63qDeciFigbyJbcDaXkIJDE7z0xzv+BvivcWWuwaN4v8AiJrVg08YGmLBp0V7Esg4WOaMQvdSxscKCJhKcEFySXXOnlfJT93RvvqaYjMZ1J30svkenad4eu9Ps47Sz0i8jhTJAMTsSSSWZmOSzEkksSSSSSSSTS3GianIhK6XeF+2IGyf0rt9B18mSOw1a605bl7cXVrewXCCz1S3ONtzbMznKkMu9MsYyyglkeKSTf8AtMQiErtsiJG2RgVR85I2seGBHIIJBHNcFLKHRrc6qPmWvqZTzCUocrgjyq30LWo7y1Nvp19HMHBDiN1CkEYO4gY575FdbpVl43juGYX0sOUI3XNwJFPI4A+bB98evPPPYJIR3yKmjDSfcVm4zwCTXZLAe1acpyuuxjHGNJqMV8zxPVoSt/cLPbtZeSoYW8gYNuIHAyMgckjd0AwSTybFzpGoaTFCNQtZLc3CeagYdRxwfQjjIOCMjIGafNZQQI6XN/vLurPbW5DqcEjJfJUHaxwVD4yQQORUqapNHcwSwQW8EcEyypCikLuU5BYklm5zjJJAJAwDivBxmKoyw0aN7Xtfy/p3PToU6iqOaV/N9fQ85+Lujy3GkWviPS2K6/oMwuNNzI6rMzMoa3Kry/mgBAgwWYqoIDEG14F8Qaf4w8MaOmk3D3GmW8S3+skqVF1rUpWRkYMqsy2oCJGWLqVaLBLQKa9N+Kfi7TdT0rw7cyPLbWVnrKXOrRyAtGsK20+yRsAhkW4MD5I+UoJCFCFh4lc+LvC2g/FG3Hw/sf7cg1s3EuuQWGoNsuLiSVHjkY5ZXI2TFYsoEDSNmNSz16mHo8uEdKjU5m07Stst7eX/AATKUnKpzzjbyOKuP+Qtq/8A2F77/wBKpabXtVvpfw003UvEurfETRbhrHU8Ti/sFuhHaqoiMkZgtcGIlomlNwqjd5kqOVBAl9Qn+F/wc8IWUWqahY2Gm21hI8v2jVdUkeJTKFiPmm4kZXU4UKr5CsSVAZiT72ExFOvRjODumedXhKE2mrHyLXC28zTfHzQIriRhFFq1igKoCVQyRsccjJyxPJHpkDp93QfCv4QeJNOvNeggt9V07VLiOdLnTdSeO3TykMISE2rIqpkOWVfvOSWyVXb44/hn4X654n0jXvAnhW6trLS3Eseq3y3AOoKYmKBEnYu4DSh/PcBh5UaIWXmN4vEQw9GU5vZf0goU5VJqKOg8ST6TpunXWiy+IYNNsL0m/wBGutVZLW1sNYiLSbS4LlUuUMokxsGEkAy9ySd3w14msp9Pt9U0fT5oFuIssLm5kE8bZ+aJvKZACrAqyckMpBPGBzS3+haH43n1rxTLZW1uthAmlXV5t2xThrgTrG7cROyNCCMguF4yEbanhJlmn1y+tV26Xe6m9xp20AI0Jij3MgHAVpRKwIGHLFwSHDH5PF15SwdOoviSVn69PX/gnsU6CVRp7dj02x8bXDOsM1vaWcYOFaCAbFycncpBJBP90ggEnDHArrbXUJL2HMhkVlIGGYMCcAgggkEEEEEdQc9DXnOl6Hc3LJLcxSRQMA4GQJJAcY2g8gHP3yNowepAB7ixjMMITcueOBnCgAKAM84AAGSSTjJOa78qr4qdJvEfLoeZj40YSXs/meYUUUV8OfSDoyEkV2RZFUglWJAYA9Dgg4PsQfert3Lotzei+n028e5VSiyG6j3Kp25VSIvlU7V+UYHyrxwMUK8a8dXPxJ1nxFf2On6L4sjsLSXbEmjWNxIrqMhZWngUklwSdgYKOAVLKSfbyPAVsfWdCnNQ7tnJjKkKUeeSb9LnqXxPl0k/DXxQI7K9Vzo94FZrtWAPkPgkCMZGe2R9RXo37SH/ACJ6/wDYS0n/ANOUFfFN54I1e2bbcfD3XonIztk8OXCnHrgxDjr+VdH8HvBFzP8AEvRbi+8LX2n2VpJJPcXFxpDRKmIXCEeYEDMJTGQAcg/MBhSR95DJ4ZXQmvbRm3rpZHh1MUqs02rLz1Prn4Jf8kaA/wCovqv/AKdLivLPhTaXV38PfDUVrbTTyLo1qxWNCxA8lBnAB4yRz71458XfBU0XxK1q4svCV/eWV3LFPbzQaW04kBhjEjExIwUmRZCVJzzk5yGPKN4RvCMf8INrPHp4fn/+N06+R0czwtNyrxj1tfX0CjjfYTcoq59iWvh2Zjm7uoYRk5WIiZyMcEFTs69iwOATjpnZ07T7KxKtBHukGP30gDPnjkDonIBGAWB6MRXzl8H/ABH8UdO8V2Omz6f4o1PSbqcLcx6va3AWJCQGmW4mXKFQpIQsVbBAXe4I+ko50cdcHGSDXhyyyhgZ8sbN9HuZ18fWqaN79C5E4yxGcsSzEnJJPUknqfc1Mj++D6iqQOCCKkWTH3vzFaqTvqcVz//Z'
                    }
                ]
            }),
            async: false,
            complete: function (returnInfo) {
                response = returnInfo;
                jsonData = JSON.parse(response.responseText);
                noteId = jsonData.data.msg_serial;
            }
        });
        it("驗證 Response status - 須為200", function () {
            expect(response.status).toEqual(200);
        });

        it("驗證 JSON Data - 要有值", function () {
            expect(jsonData).toBeDefined();
        });

        it("驗證 JSON Data Code - 須為0", function () {
            expect(jsonData.code).toEqual(0);
        });

        it("驗證 JSON Data Message - type須為string", function () {
            expect(typeof(jsonData.message)).toEqual('string');
        });

        it("驗證 JSON Data Message - 須為'success'", function () {
            expect(jsonData.message).toEqual('success');
        });
    });

    describe("編輯筆記", function () {
        var response, jsonData;

        jQuery.ajax({
            url: '../index.php?action=note-handler&ticket=' + ticket,
            type: 'POST',
            data: JSON.stringify({
                folder_id: 'sys_notebook',
                note_id: noteId,
                title: '測試新增筆記',
                content: '這是測試用的編輯過後的筆記內容',
                note_attachments: [
                    {
                        filename: 'WMsmall_test1.jpg',
                        base64: ''
                    },
                    {
                        filename: 'small_test_edit.jpg',
                        base64: '/9j/4AAQSkZJRgABAQEAYABgAAD/4gv4SUNDX1BST0ZJTEUAAQEAAAvoAAAAAAIAAABtbnRyUkdCIFhZWiAH2QADABsAFQAkAB9hY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA9tYAAQAAAADTLQAAAAAp+D3er/JVrnhC+uTKgzkNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBkZXNjAAABRAAAAHliWFlaAAABwAAAABRiVFJDAAAB1AAACAxkbWRkAAAJ4AAAAIhnWFlaAAAKaAAAABRnVFJDAAAB1AAACAxsdW1pAAAKfAAAABRtZWFzAAAKkAAAACRia3B0AAAKtAAAABRyWFlaAAAKyAAAABRyVFJDAAAB1AAACAx0ZWNoAAAK3AAAAAx2dWVkAAAK6AAAAId3dHB0AAALcAAAABRjcHJ0AAALhAAAADdjaGFkAAALvAAAACxkZXNjAAAAAAAAAB9zUkdCIElFQzYxOTY2LTItMSBibGFjayBzY2FsZWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWFlaIAAAAAAAACSgAAAPhAAAts9jdXJ2AAAAAAAABAAAAAAFAAoADwAUABkAHgAjACgALQAyADcAOwBAAEUASgBPAFQAWQBeAGMAaABtAHIAdwB8AIEAhgCLAJAAlQCaAJ8ApACpAK4AsgC3ALwAwQDGAMsA0ADVANsA4ADlAOsA8AD2APsBAQEHAQ0BEwEZAR8BJQErATIBOAE+AUUBTAFSAVkBYAFnAW4BdQF8AYMBiwGSAZoBoQGpAbEBuQHBAckB0QHZAeEB6QHyAfoCAwIMAhQCHQImAi8COAJBAksCVAJdAmcCcQJ6AoQCjgKYAqICrAK2AsECywLVAuAC6wL1AwADCwMWAyEDLQM4A0MDTwNaA2YDcgN+A4oDlgOiA64DugPHA9MD4APsA/kEBgQTBCAELQQ7BEgEVQRjBHEEfgSMBJoEqAS2BMQE0wThBPAE/gUNBRwFKwU6BUkFWAVnBXcFhgWWBaYFtQXFBdUF5QX2BgYGFgYnBjcGSAZZBmoGewaMBp0GrwbABtEG4wb1BwcHGQcrBz0HTwdhB3QHhgeZB6wHvwfSB+UH+AgLCB8IMghGCFoIbgiCCJYIqgi+CNII5wj7CRAJJQk6CU8JZAl5CY8JpAm6Cc8J5Qn7ChEKJwo9ClQKagqBCpgKrgrFCtwK8wsLCyILOQtRC2kLgAuYC7ALyAvhC/kMEgwqDEMMXAx1DI4MpwzADNkM8w0NDSYNQA1aDXQNjg2pDcMN3g34DhMOLg5JDmQOfw6bDrYO0g7uDwkPJQ9BD14Peg+WD7MPzw/sEAkQJhBDEGEQfhCbELkQ1xD1ERMRMRFPEW0RjBGqEckR6BIHEiYSRRJkEoQSoxLDEuMTAxMjE0MTYxODE6QTxRPlFAYUJxRJFGoUixStFM4U8BUSFTQVVhV4FZsVvRXgFgMWJhZJFmwWjxayFtYW+hcdF0EXZReJF64X0hf3GBsYQBhlGIoYrxjVGPoZIBlFGWsZkRm3Gd0aBBoqGlEadxqeGsUa7BsUGzsbYxuKG7Ib2hwCHCocUhx7HKMczBz1HR4dRx1wHZkdwx3sHhYeQB5qHpQevh7pHxMfPh9pH5Qfvx/qIBUgQSBsIJggxCDwIRwhSCF1IaEhziH7IiciVSKCIq8i3SMKIzgjZiOUI8Ij8CQfJE0kfCSrJNolCSU4JWgllyXHJfcmJyZXJocmtyboJxgnSSd6J6sn3CgNKD8ocSiiKNQpBik4KWspnSnQKgIqNSpoKpsqzysCKzYraSudK9EsBSw5LG4soizXLQwtQS12Last4S4WLkwugi63Lu4vJC9aL5Evxy/+MDUwbDCkMNsxEjFKMYIxujHyMioyYzKbMtQzDTNGM38zuDPxNCs0ZTSeNNg1EzVNNYc1wjX9Njc2cjauNuk3JDdgN5w31zgUOFA4jDjIOQU5Qjl/Obw5+To2OnQ6sjrvOy07azuqO+g8JzxlPKQ84z0iPWE9oT3gPiA+YD6gPuA/IT9hP6I/4kAjQGRApkDnQSlBakGsQe5CMEJyQrVC90M6Q31DwEQDREdEikTORRJFVUWaRd5GIkZnRqtG8Ec1R3tHwEgFSEtIkUjXSR1JY0mpSfBKN0p9SsRLDEtTS5pL4kwqTHJMuk0CTUpNk03cTiVObk63TwBPSU+TT91QJ1BxULtRBlFQUZtR5lIxUnxSx1MTU19TqlP2VEJUj1TbVShVdVXCVg9WXFapVvdXRFeSV+BYL1h9WMtZGllpWbhaB1pWWqZa9VtFW5Vb5Vw1XIZc1l0nXXhdyV4aXmxevV8PX2Ffs2AFYFdgqmD8YU9homH1YklinGLwY0Njl2PrZEBklGTpZT1lkmXnZj1mkmboZz1nk2fpaD9olmjsaUNpmmnxakhqn2r3a09rp2v/bFdsr20IbWBtuW4SbmtuxG8eb3hv0XArcIZw4HE6cZVx8HJLcqZzAXNdc7h0FHRwdMx1KHWFdeF2Pnabdvh3VnezeBF4bnjMeSp5iXnnekZ6pXsEe2N7wnwhfIF84X1BfaF+AX5ifsJ/I3+Ef+WAR4CogQqBa4HNgjCCkoL0g1eDuoQdhICE44VHhauGDoZyhteHO4efiASIaYjOiTOJmYn+imSKyoswi5aL/IxjjMqNMY2Yjf+OZo7OjzaPnpAGkG6Q1pE/kaiSEZJ6kuOTTZO2lCCUipT0lV+VyZY0lp+XCpd1l+CYTJi4mSSZkJn8mmia1ZtCm6+cHJyJnPedZJ3SnkCerp8dn4uf+qBpoNihR6G2oiailqMGo3aj5qRWpMelOKWpphqmi6b9p26n4KhSqMSpN6mpqhyqj6sCq3Wr6axcrNCtRK24ri2uoa8Wr4uwALB1sOqxYLHWskuywrM4s660JbSctRO1irYBtnm28Ldot+C4WbjRuUq5wro7urW7LrunvCG8m70VvY++Cr6Evv+/er/1wHDA7MFnwePCX8Lbw1jD1MRRxM7FS8XIxkbGw8dBx7/IPci8yTrJuco4yrfLNsu2zDXMtc01zbXONs62zzfPuNA50LrRPNG+0j/SwdNE08bUSdTL1U7V0dZV1tjXXNfg2GTY6Nls2fHadtr724DcBdyK3RDdlt4c3qLfKd+v4DbgveFE4cziU+Lb42Pj6+Rz5PzlhOYN5pbnH+ep6DLovOlG6dDqW+rl63Dr++yG7RHtnO4o7rTvQO/M8Fjw5fFy8f/yjPMZ86f0NPTC9VD13vZt9vv3ivgZ+Kj5OPnH+lf65/t3/Af8mP0p/br+S/7c/23//2Rlc2MAAAAAAAAALklFQyA2MTk2Ni0yLTEgRGVmYXVsdCBSR0IgQ29sb3VyIFNwYWNlIC0gc1JHQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYWVogAAAAAAAAYpkAALeFAAAY2lhZWiAAAAAAAAAAAABQAAAAAAAAbWVhcwAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACWFlaIAAAAAAAAAMWAAADMwAAAqRYWVogAAAAAAAAb6IAADj1AAADkHNpZyAAAAAAQ1JUIGRlc2MAAAAAAAAALVJlZmVyZW5jZSBWaWV3aW5nIENvbmRpdGlvbiBpbiBJRUMgNjE5NjYtMi0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYWVogAAAAAAAA9tYAAQAAAADTLXRleHQAAAAAQ29weXJpZ2h0IEludGVybmF0aW9uYWwgQ29sb3IgQ29uc29ydGl1bSwgMjAwOQAAc2YzMgAAAAAAAQxEAAAF3///8yYAAAeUAAD9j///+6H///2iAAAD2wAAwHX/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABgAGADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD61mvzuC+YiHBbGRnA6nnsMjNQR3CXMayxzrKj9GVgQfoRx2NYel6dB9oikjtYJrSa2YGU4xJuIJXAGMAZ5Oc+vJNQwSJa263klk5hBRYEEhBiRgFOQSecMT7kcnJJNqslsjnlQct2dNC0PmDzMEHOPeud+JnjrQvBWg/ablBcX86sLKyD7GmYYyzNg7I13LvfBxkAB3dEeHWmt7HTbrWbi4aJIYpGld3Cx26AAs5LEAKFUHOcDnOAcj5Y8e65fXumr4h1ozQ3Gpq13crNuMlrAuXitcYHyxK5GAoywZyA7tnooQ9vLskTKPsl3uJ4k+KfjzxJrE9tceI7qCyjj3PDphewSOY8IUeJ/O+5lnSSV1y6kDG0LyFzpmkz7fM0bSRtzjy7GJOvrtUZ6d6bo8EsNgjXC7bmX97cDIOJG5IyM5A4UcnAUDJxVyvVhSglsc8pu9kyDQ/CUc93u0Kye0u4wSLi0l8iSIEEEiQEFcjIPIyM54zXS3Wt+PPBK6S99rKeItFUGGOOVy+AJDI8fnMglWQlmwz7wA/CEAASfDzULi113yBFE9oALqZhGDINrxgAEg4HPABGSxyTwKveOrbUR4Dure2vJb6WKSJNQc7g8qR7gzlTk4DhckkkFSTgEgctSUXiFRklZntUMDGWXyxKcrq/po1/nv0ses6T4n8I+JfDulahpkF/LGLdo5IvtsYltnEshMUoEZw43A8cFWUjIIY62qS6MLLSi9hqBU2jFAL1AQPPl4J8o5OcnIxwQMcZPyf4B8Rp4V8U2uq3LTnTCwj1KKKTZ5kBBG45R+Yy3mDCkkKygjea+sNUl0cWOlF7C/Km0YoBeqCB58vBPlHJzk5GOCBjjJ5MZhXh6nL06M4aFVVY3DVJdGFjpRew1AqbRigF6gIHny8E+UcnOTkY4IGOMk1SXRhY6UXsNQKm0YoBeoCB58vBPlHJzk5GOCBjjJdqDaVLa6PEum6lI8lqVhRLxNxzPKAP9UcknOMAdQMcZLvEKWFi9pYX+j6nBNbW+3ab2PkGR3BDCMhh8x5GOQRjIJPIbHZ2W59FRkgD+Ur2giZxl9pwpHAAJIyOOMgds1YuZ4LedFaJzcRTiQyKh2ZI4yc9SAeB6jpnk0PU/DWq3t/pei6xp9/dWUyrfwWs5le1lyUAlC5MbZRhhsH5TkcGtOXT4bmaDzYt0ka5RmRxtBxnnGM/IOpzwD35nl1H0seR/GzUbuT4b6lboGktb5U02SVoyCIrm8itmIOBhgk0gGcjKgkHpXz98ZmY2V6hY7RpshCk8AkPk49TgfkK+nv2hoxH8Krlox97UtJB+UjI/tC1PRgPUfyPQ18zfFazutQFzZ6Zbz6jfSaa4FnZQvPcBTuAcxoCwQsQu8jaCQCQSM+lgmoUpNuxzVk3ONtTGop9vpfiG9jaWzsrW3RZGjIvZ2SQlSQwKIrFcEYIYhgQQVBFW5PCmpxlp7rxLbQ2qfNKUsAm1QMsQzSMFIAJyQQOpBHFazzXDQ05rs78Pw3mOIhzxp2T6tpD/C43a6jmcQxwQvJOckEqQQB6EbsE5IxtzyQBV3xz4g0200S60zRrgySX7s0hEgfZHJJ5rKGUgAbgAAQSQzEnBAHKaxbeBrSNbi98dXUmW2/up4Jmycn7qRkgcHnGBwO4p03hu3MMM+naR8RtWtriFZormz0cNG6tyCC0K5BHIIyCCMGuZZhhp1lUfNp5dj05ZficLhHh1KF3e75rvW2yXp5nOOqujI6qysCCrDIIPUEdxX1J4A1w3nw58LNf6bZ3kyaPagzzSTtJISgdmYiQZJZmJPqT2wK+PtfuPFeiF7i+8Napp1m0gRDqds4YNj7pcIgJ4YgYBxnrjNfTf7OXxW+E2u+HNA8H61DJomv2tpBZD7ZM4t7x0QqDHKDhSQgO1wnzOEUueTtmGMp4pRdPpufOYfDToNqXyPRJtaEkUKppVlC9uhS3ljeYPF8xYEHzDyGYkEg8+wxRc65NfTNcapaW2oznAEk5kUqoGAoCOoA6ngdST3rsdR0jwlZaH/bLadJLa7EcGOR9zBiACAWHqDzijRtL8Fax539nQef5WPM+eZcZzjqRnoenpXmXOk47TNO1fS9FsdK0y3f/AISH4eXSW0ESgQyanozgBMklS4aFcEnZEbq3ySFjJr1bT7uTxHpFlrGkXkVxpV/FHe2M3zxsY3jDxsQVBwcgkEAjP4DzjxDeazeeKbfxFoyLPc6JGbdrUFQl5DNJE11bgtwWZIkKksoEiR5IQuC/wtrVrpXiRV0iVZvDHi2Aa1osrAqqSugaaEAkBN64mCYLs63btjFZqrFxuieZWuO+MVteeINesfD/AIha707RZ7OK40/7PNs87UkeR3DMMh2hWOGWOJxsfMjFJPL/AHXPfs72ep2vwcj1ee4/03UbmS41GK9tt8q3Sv5EgOSAoBhA2FfkHyAjAx6F4ltYPEOmizvB5UkT+ba3MPE1rMAQJYy2QCASCCCrKzI4ZGZTzHhC3n8Ia3c+Grq/udUsNZSW9sprxY1b7WOZ4CIkjjXeu2ZERdzMt3IxyM1yVKnOmlJ27G9KpFtKx49pfgfxn4x+LmnXHivSbnSQkpm8Q6qNcAh1eFQiIkfkJEY1UK+wOXmxKodiFyvcaX8GfAGmazrl1pulQ6lp1863Pna1bC6uIpS7ZiiabOIyGyCyGQlGLOw2kei+ZYkktazgnkhJwFH5qSB6ZJPua5bTfEniDRNduE1Dwo8umz3jqt1ZXkk7ZJCwv5JBKIIhGjlSoEhlcIELSHmlinKLSaX5ncoS0V3b8Dkvibb+N/D2gW2h+AfDm7Q7ixuF+0aReLp9xY3bsVjYiNNxjRm84rCFZyQHOwESdF4b0fUNG+GOgz3Xizxs3jSddjSf2pcXscrEsQbmGaR4YYtu13wY5MKURt52szxNqus6rcNpmk+GdTa3glEgum1J9PaCYjCGP5WEyqGUuHDRkAfu5mUxjtzJYjlLWckc4ecFSfcBQSPXBB9xTWL5aaWmpEsO3K7ueP8A7S+mJe+A7+4aAmdzthtrZNjTSMFjR8AENuaUqAqjJQgHJJrh7X4YfD2PxgYbTw9HPDbW4kn3zTSJBcq6GKM5kwd6PIzqwfAji4QOS/qF9oOpfEnxDd2tjfy6bZaRsnE0aptFyz7oocMkiEKm+V1Ybw72zgkkmtj/AIRzTUvbrRtDCZsxJLcXU777vUbkIAxIwMn92FAUBEAwoC7VDwUJaTvprp623/rqLEzilyW179jrdCsNa8S6Xatrl00OmKqYt1BD3YUHDuxOQCcHrzjIA4J7K0tLWzjMdpbQ28ZO4rEgQE4AzgAc4A59qzPh9crf+EbGQshkiQwsqH7uwkAEZOCVCk/XPQit/wApfU16nPFHAeC3eorPpS2nlN5zTmeaUnAZzkcDtwR6dDx3qoLRrfR003SbiMG+1NLvS5JzsXTNYK5VGYD5LS6KGJwuHLzsuW88+XteL7eGBbMQ/ZMEOMQSxvgAg87ScckkZ9T71Z0u20G88J3GmalNa+VqEMkF5E3nBnjcMhUsqnGVJxg5Gc8HNcX1inTpqbaSb7gqcpaRi/Q6Hw1rVtrmiWuqWqSxR3KBjDMAJIHHDRSAE7ZFYFGXJIZSDyDVvVLKz1XT5bDUIjLBJgkByjKwIZXVgQUdWAZXUgqQCCCAR5h4Q8V2WjeMr3wvrmsLNe3ifalaGAD7TdJHGbm4jjYxhIptyzBVU4nF8CSEV27G68Rwyiez0i6WO4ht/tV3d38ASz062BObidhLkDCtsQEGQqQCirJJHze77VQjLfVencj2FRa22KU03iXQmMN/pFzr1jH93UrAxtOIxyXntzsO8AgYtxIXKsQkeVjrKPjHwhAxguPHEOjyr96y1KaO2uYs8jdHcqJlyMEbgMggjgivO/H3xB1KW7EHhPx3rt7blHS+e40+KzhebJDxxReSl1CikMuTL5g6BwVDtzmh+M9V03Uv7Q1DSLbXp/JeGJrjWdQUwoxRmC+fLcD5jHGSQFI24JIPFVsujUjdrXpbQ9LC46rSdm1bzPYLbxh4bnvVKeOLPVmViYbDSplu7mcjOCIrdTI4AySgUgAEk4Bxa1HUfFOuQSWWkeGtV0q1mBV9RvYVWTyz0eGAByWIyMTCMoSpKOQyDxTWvGWq6jqbahp2kwaBO8SwzNb63qDeciFigbyJbcDaXkIJDE7z0xzv+BvivcWWuwaN4v8AiJrVg08YGmLBp0V7Esg4WOaMQvdSxscKCJhKcEFySXXOnlfJT93RvvqaYjMZ1J30svkenad4eu9Ps47Sz0i8jhTJAMTsSSSWZmOSzEkksSSSSSSSTS3GianIhK6XeF+2IGyf0rt9B18mSOw1a605bl7cXVrewXCCz1S3ONtzbMznKkMu9MsYyyglkeKSTf8AtMQiErtsiJG2RgVR85I2seGBHIIJBHNcFLKHRrc6qPmWvqZTzCUocrgjyq30LWo7y1Nvp19HMHBDiN1CkEYO4gY575FdbpVl43juGYX0sOUI3XNwJFPI4A+bB98evPPPYJIR3yKmjDSfcVm4zwCTXZLAe1acpyuuxjHGNJqMV8zxPVoSt/cLPbtZeSoYW8gYNuIHAyMgckjd0AwSTybFzpGoaTFCNQtZLc3CeagYdRxwfQjjIOCMjIGafNZQQI6XN/vLurPbW5DqcEjJfJUHaxwVD4yQQORUqapNHcwSwQW8EcEyypCikLuU5BYklm5zjJJAJAwDivBxmKoyw0aN7Xtfy/p3PToU6iqOaV/N9fQ85+Lujy3GkWviPS2K6/oMwuNNzI6rMzMoa3Kry/mgBAgwWYqoIDEG14F8Qaf4w8MaOmk3D3GmW8S3+skqVF1rUpWRkYMqsy2oCJGWLqVaLBLQKa9N+Kfi7TdT0rw7cyPLbWVnrKXOrRyAtGsK20+yRsAhkW4MD5I+UoJCFCFh4lc+LvC2g/FG3Hw/sf7cg1s3EuuQWGoNsuLiSVHjkY5ZXI2TFYsoEDSNmNSz16mHo8uEdKjU5m07Stst7eX/AATKUnKpzzjbyOKuP+Qtq/8A2F77/wBKpabXtVvpfw003UvEurfETRbhrHU8Ti/sFuhHaqoiMkZgtcGIlomlNwqjd5kqOVBAl9Qn+F/wc8IWUWqahY2Gm21hI8v2jVdUkeJTKFiPmm4kZXU4UKr5CsSVAZiT72ExFOvRjODumedXhKE2mrHyLXC28zTfHzQIriRhFFq1igKoCVQyRsccjJyxPJHpkDp93QfCv4QeJNOvNeggt9V07VLiOdLnTdSeO3TykMISE2rIqpkOWVfvOSWyVXb44/hn4X654n0jXvAnhW6trLS3Eseq3y3AOoKYmKBEnYu4DSh/PcBh5UaIWXmN4vEQw9GU5vZf0goU5VJqKOg8ST6TpunXWiy+IYNNsL0m/wBGutVZLW1sNYiLSbS4LlUuUMokxsGEkAy9ySd3w14msp9Pt9U0fT5oFuIssLm5kE8bZ+aJvKZACrAqyckMpBPGBzS3+haH43n1rxTLZW1uthAmlXV5t2xThrgTrG7cROyNCCMguF4yEbanhJlmn1y+tV26Xe6m9xp20AI0Jij3MgHAVpRKwIGHLFwSHDH5PF15SwdOoviSVn69PX/gnsU6CVRp7dj02x8bXDOsM1vaWcYOFaCAbFycncpBJBP90ggEnDHArrbXUJL2HMhkVlIGGYMCcAgggkEEEEEdQc9DXnOl6Hc3LJLcxSRQMA4GQJJAcY2g8gHP3yNowepAB7ixjMMITcueOBnCgAKAM84AAGSSTjJOa78qr4qdJvEfLoeZj40YSXs/meYUUUV8OfSDoyEkV2RZFUglWJAYA9Dgg4PsQfert3Lotzei+n028e5VSiyG6j3Kp25VSIvlU7V+UYHyrxwMUK8a8dXPxJ1nxFf2On6L4sjsLSXbEmjWNxIrqMhZWngUklwSdgYKOAVLKSfbyPAVsfWdCnNQ7tnJjKkKUeeSb9LnqXxPl0k/DXxQI7K9Vzo94FZrtWAPkPgkCMZGe2R9RXo37SH/ACJ6/wDYS0n/ANOUFfFN54I1e2bbcfD3XonIztk8OXCnHrgxDjr+VdH8HvBFzP8AEvRbi+8LX2n2VpJJPcXFxpDRKmIXCEeYEDMJTGQAcg/MBhSR95DJ4ZXQmvbRm3rpZHh1MUqs02rLz1Prn4Jf8kaA/wCovqv/AKdLivLPhTaXV38PfDUVrbTTyLo1qxWNCxA8lBnAB4yRz71458XfBU0XxK1q4svCV/eWV3LFPbzQaW04kBhjEjExIwUmRZCVJzzk5yGPKN4RvCMf8INrPHp4fn/+N06+R0czwtNyrxj1tfX0CjjfYTcoq59iWvh2Zjm7uoYRk5WIiZyMcEFTs69iwOATjpnZ07T7KxKtBHukGP30gDPnjkDonIBGAWB6MRXzl8H/ABH8UdO8V2Omz6f4o1PSbqcLcx6va3AWJCQGmW4mXKFQpIQsVbBAXe4I+ko50cdcHGSDXhyyyhgZ8sbN9HuZ18fWqaN79C5E4yxGcsSzEnJJPUknqfc1Mj++D6iqQOCCKkWTH3vzFaqTvqcVz//Z'
                    }
                ]
            }),
            async: false,
            complete: function (returnInfo) {
                response = returnInfo;
                jsonData = JSON.parse(response.responseText);
            }
        });
        it("驗證 Response status - 須為200", function () {
            expect(response.status).toEqual(200);
        });

        it("驗證 JSON Data - 要有值", function () {
            expect(jsonData).toBeDefined();
        });

        it("驗證 JSON Data Code - 須為0", function () {
            expect(jsonData.code).toEqual(0);
        });

        it("驗證 JSON Data Message - type須為string", function () {
            expect(typeof(jsonData.message)).toEqual('string');
        });

        it("驗證 JSON Data Message - 須為'success'", function () {
            expect(jsonData.message).toEqual('success');
        });
    });

    describe("雲端筆記分享", function () {
        var response, jsonData;
        describe("製作分享Key", function () {
            var response,
                jsonData,
                possible = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789",
                keyLength = 16,
                shareKey = '',
                i;
            for (i = 0; i < keyLength; i++) {
                shareKey += possible.charAt(Math.floor(Math.random() * possible.length));
            }
            shareKey += new Date().getTime();

            jQuery.ajax({
                url: '../index.php?action=create-note-share-key&ticket=' + ticket,
                type: 'POST',
                data: JSON.stringify({
                    folderId: folderId,
                    noteId: noteId,
                    shareKey: shareKey
                }),
                async: false,
                complete: function (returnInfo) {
                    response = returnInfo;
                    jsonData = JSON.parse(response.responseText);
                    shareURL = jsonData.shareURL;
                }
            });
            it("驗證 Response status - 須為200", function () {
                expect(response.status).toEqual(200);
            });

            it("驗證 JSON Data - 要有值", function () {
                expect(jsonData).toBeDefined();
            });

            it("驗證 JSON Data Code - 須為0", function () {
                expect(jsonData.code).toEqual(0);
            });

            it("驗證 JSON Data Message - type須為string", function () {
                expect(typeof(jsonData.message)).toEqual('string');
            });

            it("驗證 JSON Data Message - 須為'success'", function () {
                expect(jsonData.message).toEqual('success');
            });

            describe("驗證回傳資料的各項參數與是否符合API設定的型態", function () {
                describe("驗證 JSON Data > data > shareKey", function () {
                    it("要有值", function () {
                        expect(jsonData.data.shareURL).toBeDefined();
                    });
                    it("type須為string", function () {
                        expect(typeof(jsonData.data.shareURL)).toEqual('string');
                    });
                });
            });
        });
    });

    describe("刪除筆記", function () {
        var response, jsonData;

        jQuery.ajax({
            url: '../index.php?action=delete-note',
            type: 'GET',
            data: {
                ticket: ticket,
                folder_id: folderId,
                note_id: noteId
            },
            async: false,
            complete: function (returnInfo) {
                response = returnInfo;
                jsonData = JSON.parse(response.responseText);
            }
        });
        it("驗證 Response status - 須為200", function () {
            expect(response.status).toEqual(200);
        });

        it("驗證 JSON Data - 要有值", function () {
            expect(jsonData).toBeDefined();
        });

        it("驗證 JSON Data Code - 須為0", function () {
            expect(jsonData.code).toEqual(0);
        });

        it("驗證 JSON Data Message - type須為string", function () {
            expect(typeof(jsonData.message)).toEqual('string');
        });

        it("驗證 JSON Data Message - 須為'success'", function () {
            expect(jsonData.message).toEqual('success');
        });
    });
});
